version: '2.3'

services:
  aspnetcore:
    image: aspnetcore
    build: ./aspnetcore/
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dialogdatabase
      MONGO_INITDB_ROOT_PASSWORD: erN9XzDa785DSKrB
    volumes:
      # Persist data
      - ./MongoData:/data/db
    ports:
      - 27000:27017
  smartkg:
    image: smartkg
    build: ./smartkg/
    ports:
      - 8082:8080
  ui:
    image: ui
    build: ./ui/
    ports:
      - 8083:8080

